server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dpspring
    username: pguser
    password: pgpass
#  flyway.enabled: true
#  flyway:
#    locations: classpath:db.migrations
#    schemas: file
#    url: jdbc:postgresql://localhost:5432/dpspring
#    user: pguser
#    password: pgpass
#    baselineOnMigrate: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        id:
          new_generator_mappings: false
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dms-spring-realm
springdoc:
  swagger-ui:
    oauth:
      client-id: dms-spring-client-id
      client-secret: aMfTPmGMQ0K6sxs0zTyqeV3pkAejkq8p
      use-pkce-with-authorization-code-grant: false
      scopes: openid,profile,roles
      additional-query-string-params:
        kc_idp_hint:
    display-oauth2-login: true


keycloak:
  realm: dms-spring-realm
  auth-server-url: http://localhost:8080
  resource: dms-spring-client-id
  credentials:
    secret: aMfTPmGMQ0K6sxs0zTyqeV3pkAejkq8p
  cors: true
keycloak-admin:
  username: admin1
  password: admin1

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        jdbc:
          core: DEBUG
        security: DEBUG